// This file was auto-generated by Fern from our API Definition.

package client

import (
	context "context"
	sdkgo "github.com/universal-sandbox/sdk-go"
	aio "github.com/universal-sandbox/sdk-go/aio"
	browser "github.com/universal-sandbox/sdk-go/browser"
	codeinterpreter "github.com/universal-sandbox/sdk-go/codeinterpreter"
	core "github.com/universal-sandbox/sdk-go/core"
	option "github.com/universal-sandbox/sdk-go/option"
	sandboxes "github.com/universal-sandbox/sdk-go/sandboxes"
	tokens "github.com/universal-sandbox/sdk-go/tokens"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	CodeInterpreter *codeinterpreter.Client
	Browser         *browser.Client
	Aio             *aio.Client
	Sandboxes       *sandboxes.Client
	Tokens          *tokens.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:          options.ToHeader(),
		CodeInterpreter: codeinterpreter.NewClient(opts...),
		Browser:         browser.NewClient(opts...),
		Aio:             aio.NewClient(opts...),
		Sandboxes:       sandboxes.NewClient(opts...),
		Tokens:          tokens.NewClient(opts...),
	}
}

// Check service health status.
func (c *Client) CheckHealth(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdkgo.HealthStatus, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.sandbox.ai-infra.org"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/health"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *sdkgo.HealthStatus
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			MaxAttempts:     options.MaxAttempts,
			Headers:         headers,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// List available regions for all providers.
func (c *Client) ListRegions(
	ctx context.Context,
	opts ...option.RequestOption,
) (interface{}, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.sandbox.ai-infra.org"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/regions"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response interface{}
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			MaxAttempts:     options.MaxAttempts,
			Headers:         headers,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Get resource limits and current usage.
func (c *Client) GetLimits(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdkgo.LimitsResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.sandbox.ai-infra.org"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/limits"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *sdkgo.LimitsResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			MaxAttempts:     options.MaxAttempts,
			Headers:         headers,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
