// This file was auto-generated by Fern from our API Definition.

package sandbox

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/universal-sandbox/sdk-go/core"
)

type ListRequest struct {
	IncludeDeleted *bool `json:"-" url:"include_deleted,omitempty"`
}

// Response for delete operations.
type DeleteResponse struct {
	Success   bool   `json:"success" url:"success"`
	Message   string `json:"message" url:"message"`
	SandboxId string `json:"sandbox_id" url:"sandbox_id"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (d *DeleteResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeleteResponse) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

func (d *DeleteResponse) GetSandboxId() string {
	if d == nil {
		return ""
	}
	return d.SandboxId
}

func (d *DeleteResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties

	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Response for listing sandboxes.
type SandboxListResponse struct {
	Sandboxes []*SandboxResponse `json:"sandboxes,omitempty" url:"sandboxes,omitempty"`
	Total     int                `json:"total" url:"total"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SandboxListResponse) GetSandboxes() []*SandboxResponse {
	if s == nil {
		return nil
	}
	return s.Sandboxes
}

func (s *SandboxListResponse) GetTotal() int {
	if s == nil {
		return 0
	}
	return s.Total
}

func (s *SandboxListResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SandboxListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SandboxListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SandboxListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SandboxListResponse) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
