// This file was auto-generated by Fern from our API Definition.

package sandbox

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/universal-sandbox/sdk-go/core"
)

type GetRequest struct {
	AdminKey        *string `json:"-" url:"-"`
	IncludeRawToken *bool   `json:"-" url:"include_raw_token,omitempty"`
}

type CreateTokenRequest struct {
	AdminKey *string `json:"-" url:"-"`
	// Token name
	Name string `json:"name" url:"-"`
	// User ID
	UserId string `json:"user_id" url:"-"`
	// Token scopes
	Scopes []string `json:"scopes,omitempty" url:"-"`
	// Token expiration in days
	ExpiresInDays *int `json:"expires_in_days,omitempty" url:"-"`
	// Revoke existing tokens for user
	RevokeExisting *bool `json:"revoke_existing,omitempty" url:"-"`
}

type RevokeRequest struct {
	AdminKey *string `json:"-" url:"-"`
}

// Response containing token details.
type TokenResponse struct {
	Id           string   `json:"id" url:"id"`
	UserId       string   `json:"user_id" url:"user_id"`
	Name         string   `json:"name" url:"name"`
	TokenPrefix  string   `json:"token_prefix" url:"token_prefix"`
	Scopes       []string `json:"scopes,omitempty" url:"scopes,omitempty"`
	CreatedAt    string   `json:"created_at" url:"created_at"`
	ExpiresAt    *string  `json:"expires_at,omitempty" url:"expires_at,omitempty"`
	RevokedAt    *string  `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`
	LastUsedAt   *string  `json:"last_used_at,omitempty" url:"last_used_at,omitempty"`
	DisplayToken *string  `json:"display_token,omitempty" url:"display_token,omitempty"`
	RawToken     *string  `json:"raw_token,omitempty" url:"raw_token,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TokenResponse) GetId() string {
	if t == nil {
		return ""
	}
	return t.Id
}

func (t *TokenResponse) GetUserId() string {
	if t == nil {
		return ""
	}
	return t.UserId
}

func (t *TokenResponse) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TokenResponse) GetTokenPrefix() string {
	if t == nil {
		return ""
	}
	return t.TokenPrefix
}

func (t *TokenResponse) GetScopes() []string {
	if t == nil {
		return nil
	}
	return t.Scopes
}

func (t *TokenResponse) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}

func (t *TokenResponse) GetExpiresAt() *string {
	if t == nil {
		return nil
	}
	return t.ExpiresAt
}

func (t *TokenResponse) GetRevokedAt() *string {
	if t == nil {
		return nil
	}
	return t.RevokedAt
}

func (t *TokenResponse) GetLastUsedAt() *string {
	if t == nil {
		return nil
	}
	return t.LastUsedAt
}

func (t *TokenResponse) GetDisplayToken() *string {
	if t == nil {
		return nil
	}
	return t.DisplayToken
}

func (t *TokenResponse) GetRawToken() *string {
	if t == nil {
		return nil
	}
	return t.RawToken
}

func (t *TokenResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TokenResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenResponse) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
